version: '3.8'

services:
  fuego-testnet-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUILD_TYPE: Release
        ENABLE_OPTIMIZATIONS: "ON"
    container_name: fuego-testnet-node
    restart: unless-stopped
    ports:
      - "20808:20808"  # P2P port
      - "28180:28180"  # RPC port
    volumes:
      - fuego-testnet-data:/home/fuego/.fuego
      - ./config:/home/fuego/config:ro
    environment:
      - FUEGO_LOG_LEVEL=2
    networks:
      - fuego-testnet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:28180/getinfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    entrypoint: ["fuegod"]
    command: [
      "--data-dir=/home/fuego/.fuego",
      "--rpc-bind-ip=0.0.0.0",
      "--rpc-bind-port=28180",
      "--p2p-bind-ip=0.0.0.0",
      "--p2p-bind-port=20808",
      "--testnet",
      "--log-level=2"
    ]

  fuego-testnet-wallet:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fuego-testnet-wallet
    restart: unless-stopped
    ports:
      - "8070:8070"   # Wallet RPC port
    volumes:
      - fuego-testnet-wallet-data:/home/fuego/.fuego-wallet
    environment:
      - FUEGO_LOG_LEVEL=2
    networks:
      - fuego-testnet-network
    depends_on:
      - fuego-testnet-node
    entrypoint: ["walletd"]
    command: [
      "--daemon-host=fuego-testnet-node",
      "--daemon-port=28180",
      "--bind-port=8070",
      "--bind-ip=0.0.0.0",
      "--wallet-dir=/home/fuego/.fuego-wallet",
      "--testnet",
      "--log-level=2"
    ]

  # Optional: Nginx reverse proxy for web access
  nginx:
    image: nginx:alpine
    container_name: fuego-testnet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - fuego-testnet-network
    depends_on:
      - fuego-testnet-node
      - fuego-testnet-wallet
    profiles:
      - web

volumes:
  fuego-testnet-data:
    driver: local
  fuego-testnet-wallet-data:
    driver: local

networks:
  fuego-testnet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
