name: Test Dynamic Supply

on:
  push:
    branches: [ master, dynamigo-release-v10 ]
    paths: 
      - 'src/CryptoNoteCore/DynamicMoneySupply.*'
      - 'src/CryptoNoteCore/DepositIndex.*'
      - 'src/CryptoNoteCore/Currency.*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-dynamic-supply:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ninja-build \
            cmake \
            git \
            libboost-all-dev \
            pkg-config \
            ca-certificates \
            libicu-dev

      - name: Configure
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests (ctest)
        run: ctest --test-dir build --output-on-failure

      - name: Verify dynamic supply symbols
        run: |
          echo "Verifying dynamic supply symbols in CryptoNoteCore..."
          nm build/src/libCryptoNoteCore.a | grep -Ei "DynamicMoneySupply|getAdjustedMoneySupply|getCirculatingSupply" || true

      - name: Verify dynamic supply constants
        run: |
          echo "Verifying dynamic supply constants..."
          grep -R "8000008800000008" src/CryptoNoteCore/ || true

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dynamic-supply-test-results
          path: |
            build/CTestTestfile.cmake
            build/Testing/Temporary/LastTest.log
            build/CMakeFiles/CMakeOutput.log
          retention-days: 30
